document.write("<html>");
document.write("    <head>");
document.write("    <title>Your Title Here</title>");
document.write("    ");
document.write("    ");
document.write("    	<style type=\"text/css\">");
document.write("		.green {");
document.write("			background-color: green;");
document.write("		}");
document.write("		.blue {");
document.write("			background: rgb(48,36,255);");
document.write("			background: linear-gradient(90deg, rgba(48,36,255,1) 0%, rgba(6,6,114,1) 49%, rgba(5,45,255,1) 100%); ");
document.write("		}");
document.write("		");
document.write("		a {");
document.write("        	color: #fff;");
document.write("		margin: 0;");
document.write("		text-decoration: none;");
document.write("			}");
document.write("");
document.write("	</style>");
document.write("    ");
document.write("    ");
document.write("    </head>");
document.write("    ");
document.write("");
document.write("    <body bgcolor=\"FFFFFF\">");
document.write("        <center><img src=\"wtools.jpg\" align=\"bottom\"> </center>");
document.write("        <hr>");
document.write("        <a href=\"http://wtools.io\">Best Online Web Tools</a>is a link to another nifty site");
document.write("        <h1>This is a Header</h1>");
document.write("        <h2>This is a Medium Header</h2>");
document.write("        Send me mail at <a href=\"mailto:support@example.com\">support@example.com</a>.");
document.write("        <p> This is a new paragraph!</p>");
document.write("        <p> <b>This is a new paragraph!</b></p>");
document.write("        <br> <b><i>This is a new sentence without a paragraph break, in bold italics.</i></b>");
document.write("        <hr>");
document.write("    </body>");
document.write("</html>");
